export enum EnumIconName {
	pill = 'pill',
	home = 'home',
	back = 'back',
	info = 'info',
	gift = 'gift',
	mail = 'mail',
	star = 'star',
	sort = 'sort',
	clear = 'clear',
	right = 'right',
	cream = 'cream',
	search = 'search',
	remove = 'remove',
	options = 'options',
	history = 'history',
	language = 'language',
	settings = 'settings',
	analytic = 'analytic',
	medicine = 'medicine',
	bell = 'notification',
	bellOff = 'notificationOff',
}
