export enum EnumIconName {
	pill = 'pill',
	home = 'home',
	plus = 'plus',
	back = 'back',
	info = 'info',
	mail = 'mail',
	star = 'star',
	sort = 'sort',
	clear = 'clear',
	right = 'right',
	money = 'money',
	cream = 'cream',
	search = 'search',
	delete = 'delete',
	options = 'options',
	history = 'history',
	language = 'language',
	settings = 'settings',
	analytic = 'analytic',
	addMedicine = 'addMedicine',
	notification = 'notification',
	notificationOff = 'notificationOff',
}
